# Generated by Django 2.1.4 on 2019-01-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('Hmusic_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'music_history',
            },
        ),
    ]
