# Generated by Django 2.1.4 on 2019-01-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('follow_id', models.IntegerField()),
            ],
            options={
                'db_table': 'friend',
            },
        ),
    ]
