# Generated by Django 2.1.4 on 2019-01-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_phone', models.CharField(max_length=11, unique=True)),
                ('user_nickname', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('保密', '保密')], default='保密', max_length=2)),
                ('birthday', models.CharField(default='1770-01-01', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('attention', models.IntegerField(default=0)),
                ('Fan', models.IntegerField(default=0)),
                ('image', models.CharField(default='user_pic/default/user.jpg', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
