# Generated by Django 2.1.5 on 2019-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.AutoField(primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=30)),
                ('picture', models.CharField(default='', max_length=264)),
                ('introduce', models.TextField(default='')),
                ('fanNo', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'singer',
            },
        ),
    ]
